name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Install dependencies
      run: go mod download

    - name: Set test env vars
      uses: c-py/action-dotenv-to-setenv@v5
      with:
        env-file: ./testing.env

    - name: Run tests with code coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # optional
        files: ./coverage.out
        fail_ci_if_error: true
